POST http://127.0.0.1:4200/auth/login
Content-Type: application/json

{
    "email":"geraldo@gmail.com",
    "password":"1234"
}

####
GET http://127.0.0.1:4200/comment/get/byPost?postId=8

####
PATCH http://127.0.0.1:4200/comment/like?id=4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImRiNDE4ZDYyLTI5YzktNDAyOC1iYTg1LWEwZDRiMTJjYjJlOCIsInR5cGUiOiJOb3JtYWxVc2VyIiwiZXhwIjoxNzM4MjQ3MTM0LCJqdGkiOiJiYzY5NTlkZi1kMjRlLTRhMGMtYjczYS1jNjMzMjEzZTA2YTgifQ.zVVWWpcRouTi7ATsFqcTTfi0YzmY50-mQ2iTgm2Vgqc